env:
  browser: true
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - off
    - 0
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
